import "./globals.css";
import { Raleway } from "next/font/google";

const raleway = Raleway({
  display: "swap",
  weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
  subsets: ["latin-ext"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway.className}>{children}</body>
    </html>
  );
}
